### PR TITLE
Header updates

### PR DESCRIPTION
**Pull request by Brandonprs**
Cleans up the header CSS and what displays a bit. 
We should discuss what else should go in the header for a washer/driver

### CODE REVIEW

**Comment by johncburns1** [comment]
Lemme look over these commits when I get home.  I know that I have to chat
with Simon, our other front-end guy and get you on the same page because he
has been doing some work on the CSS as well.  So I want to make sure that
before I merge that none of your code or his code are conflicting/being
written over.

best,

Jack Burns

**Comment by Brandonprs** [comment]
Sounds good.
If Simon is routinely committing / merging in master it shouldn't be an
issue. Have you guys thought about using a story tracker like pivotal or
jira? It'd be a good tool to use to track issues and features so that I
don't start working on something that Simon is already working on.

B

**Comment by johncburns1** [comment]
No I have not but that is a great idea! I have been really slacking on
documentation because I have been doing a lot of the code myself or
directly with others but it is getting chaotic so that is my goal for
tomorrow.

Best,

Jack Burns

**Comment by Brandonprs** [comment]
Let me know if you want assistance setting things up, I've used a few
different project management tools; they're all pretty straight forward so
you'll be fine, let me know if you want help writing "stories."

**Comment by johncburns1** [comment]
Hi Brandon,

So as you have noticed, the project has gotten to a point in which
organization is going to be essential for completing it.  I am going to
spend the next couple of days writing documentation, interviewing clients,
and creating well defined user stories so that everybody can be on the same
page and knows what we still need to do to get this thing finished.

Until recently, it has been mostly me but now that I have some more help, I
need to take some time to get everybody on the same page.  Let me get back
to you either today or tomorrow with some more concrete planning and tasks.

Best,

Jack Burns

**Comment by Brandonprs** [comment]
Solid, well let me know how I can help.

B

**Comment by johncburns1** [comment]
Brandon,

Just started a new pivotal tracker with Our current Epic and stories for
this iteration, which will last for this week and maybe next week (I do not
have a good gauge on how long iterations will be yet).  Let me know what
you think of them and I would love some feedback on what more I can explain
and what information you might want to see on there.  Could you send my
your pivotal tracker account info so that I can invite you to the project?

Best,

Jack Burns

**Comment by Brandonprs** [comment]
Cool I'll take a look this evening.

Can you add brandonprs@gmail.com to the Pivotal account? If not, my
username is brandonparis and I'm using my work email for my work Pivotal,
so I'm assuming you should be able to use the same email for two different
Pivotal accounts. That email is brandon@voxel51.com. I would prefer to use
brandonprs@gmail.com if you can invite me there.

**Comment by johncburns1** [comment]
Brandon,

Just sent you the invite.

Best,

Jack Burns

**Comment by Brandonprs** [comment]
Great! Everything looks good, I appreciate the detail you put into each
story.

Not that it really matters, but agile companies tend to use the fibonacci
scale for story points. If you ever decide to stick to a sprint schedule
(1-2 weeks), you might want to adopt the scale.
1 for trivial tasks
2 for trivial tasks that might take a few hours
3 for something that might take a day
5 for something that make take a few days or so
8 for something that could take a whole sprint
13 for something that needs to be broken up into smaller tasks :)

Obviously, interpret those points as you deem fit for the team. But that's
the general gist. It's a good way to look at velocity over time, but don't
concern yourself with that right now. That's for a project manager!

**Comment by Brandonprs** [comment]
I just added a story that I've been working on, a general reworking of the
site so that it more closely matches the screenshots in the Wiki. Let me
know if there are more updated designs that I should be trying to match
instead of the ones in the Wiki.

Also, everything I've suggested are just that: suggestions. They're not the
only way of doing things, just the ways that I've seen in my career so far.
So if you're ever not down with an idea, don't feel obliged to give it a
try.

**Pull request merged**
